(set-language-environment 'UTF-8)
(setq default-buffer-file-coding-system 'mule-utf-8-unix)
(prefer-coding-system 'mule-utf-8-unix)
(set-terminal-coding-system 'mule-utf-8-unix)
(set-keyboard-coding-system 'mule-utf-8-unix)
(setq-default coding-system-for-read 'mule-utf-8-unix)
(setq-default coding-system-for-write 'mule-utf-8-unix)
(setq selection-coding-system 'mule-utf-8-unix)
(setq default-process-coding-system 'mule-utf-8-unix)
(put-charset-property 'cyrillic-iso8859-5 'preferred-coding-system 'mule-utf-8-unix)
